name: CI
on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]
jobs:
  tests:
    runs-on: 'Ubuntu-20.04'
    strategy:
      fail-fast: false
      matrix:
        php: ['7.4', '8.0', '8.1', '8.2']

    name: Tests PHP ${{ matrix.php }}
    steps:
      -   uses: actions/checkout@v2
      -   uses: shivammathur/setup-php@v2
          with:
            php-version: '${{ matrix.php }}'
            coverage: none
            ini-values: 'memory_limit=-1'
      -   uses: "ramsey/composer-install@v2"
      -   name: Run Unit tests
          run: vendor/bin/phpunit
  style:
    runs-on: 'Ubuntu-20.04'
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.2' ]
    name: Style PHP ${{ matrix.php }}
    steps:
      -   uses: actions/checkout@v2
      -   uses: shivammathur/setup-php@v2
          with:
            php-version: '${{ matrix.php }}'
            coverage: none
            ini-values: 'memory_limit=-1'
      -   uses: "ramsey/composer-install@v2"
      -   name: Run Style checks
          run: vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.php -v --dry-run --stop-on-violation